####################################################################################
# 系统运行相关配置
####################################################################################
system:
  # 监听地址
  listen: 0.0.0.0
  # 监听端口
  port: 10001
  # API 接口前缀
  api-prefix: /api
  # API 接口版本
  api-version: v1
  # 日志级别:
  #   0: ACCESS 请求访问日志，不受配置影响（默认）
  #   1: DEBUG 级别日志
  #   2: INFO 级别日志
  #   3: WARNING 级别日志
  #   4: ERROR 级别日志
  #   5: SYSTEM 关闭普通日志，只打印系统日志
  log-level: 2

####################################################################################
# 数据库配置
####################################################################################
mysql:
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 13306
  # 数据库
  database: phoenix
  # 用户名
  username: root
  # 密码
  password: 123456
  # 字符集
  charset: utf8mb4
  # 排序规则
  collation: utf8mb4_bin
  # 超时时间，单位毫秒
  timeout: 1000
  # 额外参数
  extra-param: parseTime=True&loc=Local
  # 最大打开链接数
  max-open-conns: 100
  # 最大空闲连接数
  max-idle-conns: 10
  # 空闲连接最大超时时间，单位分钟
  max-idle-time: 30

####################################################################################
# Redis 配置
####################################################################################
redis:
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 16379
  # 数据库
  database: 0
  # 密码，没有就不设置
  password: ""
  # 连接超时时间，单位秒
  timeout: 5
  # 最大连接数，一般比 CPU 核数 4 倍少一点
  max-open-conns: 12
  # 最小空闲连接
  min-idle-conns: 5
  # 最大空闲连接
  max-idle-conns: 10
  # 最大空闲时长，单位分钟
  max-idle-time: 10

####################################################################################
# JWT 配置
####################################################################################
jwt:
  # 领域，用于区分不同的认证范围
  realm: phoenix
  # 用于签名和验证 JWT 令牌的密钥
  # 一般是一个随机生成的字符串，在中间件生成 JWT 令牌时，会使用这个密钥对令牌进行签名
  key: SNDAhUAD3SA7h06f72H8
  # Token 超时时间，单位秒，默认 1 天，Redis 中有效期也是如此
  timeout: 86400

####################################################################################
# 登录配置
####################################################################################
login:
  # 密码错误上限，达到上限锁定账户
  wrong-times: 5
  # 账户锁定时间，单位秒，默认 5 分钟
  lock-time: 300
  # 是否允许多设备登录
  multi-devices: false
  # 重置密码 Token 过期时间
  reset-token-time: 300
